apiVersion: v1
automountServiceAccountToken: true
kind: ServiceAccount
metadata:
  name: leader-election-demo-sa
  labels:
    app: leader-election-demo
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: leader-election-demo-role
  labels:
    app: leader-election-demo
rules:
  - apiGroups:
      - coordination.k8s.io
    resources:
      - leases
    verbs:
      - '*'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: leader-election-demo-rolebinding
  labels:
    app: leader-election-demo
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: leader-election-demo-role
subjects:
  - kind: ServiceAccount
    name: leader-election-demo-sa
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: leader-election-demo
  labels:
    app: leader-election-demo
spec:
  replicas: 3
  selector:
    matchLabels:
      app: leader-election-demo
  template:
    metadata:
      labels:
        app: leader-election-demo
    spec:
      serviceAccountName: leader-election-demo-sa
      automountServiceAccountToken: true
      containers:
        - name: leader-election-node
          image: quay.io/cbrgm/leader-election-node:latest
          args:
            - "--node-id=$(POD_NAME)"
            - "--leaselock.name=leader-election-demo"
            - "--leaselock.namespace=default"
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.name
